### PR TITLE
Use latest cinnamon, akka.sbr and play2-maven-plugin versions.

### PR DESCRIPTION
**Pull request by hughesj**
Updated cinnamon to 2.11.1 and akka.sbr to 1.1.9. I had trouble with play2-maven-plugin 1.0.0-rc3 so updated to 1.0.0-rc5

Signed-off-by: Jeremy Hughes <Jeremy.Hughes@uk.ibm.com>

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @hughesj,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by alanngai** [comment]
hi @hughesj, you'll need to sign the CLA before we can merge this in

**Comment by hughesj** [comment]
hi @alanngai thanks, yes. I submitted this then went on vacation. I'm on it.

**Comment by hughesj** [comment]
Hi @alanngai I got IBM legal approval to agree to the CLA. Hopefully this is ok to merge now.

**Pull request merged**
